### Start the stream
POST http://localhost:8080/api/stream/start
Content-Type: application/json

### Stop the stream
POST http://localhost:8080/api/stream/stop
Content-Type: application/json

### Get stream status
GET http://localhost:8080/api/stream/status
